# -------------------部署需要修改---------------------
bots:
  config:
    logs: false
    enable-proxy: false
    background-group-id: -1002756411889
    notify-chat-id: -1002756411889
    tokens:
      BOT_TOKEN: 8570133524:AAEYNCazKDL7TJVD_f4ub0JATCeL91TpCy4
    qr-code-path: /usr/local/qr_code/
    history-url: http://localhost:8813/collect/td/history
# -------------------部署需要修改---------------------

mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true

  global-config:
    # 全局配置
    banner: false
    db-config:
      table-prefix: t_
      # 数据库配置
      id-type: auto
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Qj683k2^11299%nkjb
    url: jdbc:mysql://127.0.0.1:3306/search_engin?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
  elasticsearch:
    uris:
      - http://localhost:9200
    username: elastic
    password: umEjOIAMYkf3vPq9YEaB
    connection-timeout: 5000
    socket-timeout: 60000
  data:
    elasticsearch:
      repositories:
        enabled: true
  redis:
    host: localhost
    port: 6379
    database: 0
    password: Qj683k2^11299%nkjb
logging:
  level:
    com.db.bots: ERROR