# -------------------部署需要修改---------------------
bots:
  config:
    logs: false
    enable-proxy: false
    background-group-id: 123456789001
    tokens:
      BOT_TOKEN: 7625159298:AAFGjgPTBlPtc2TaNfFo7Ph2FAZgVjK9Rno

# -------------------部署需要修改---------------------

mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true

  global-config:
    # 全局配置
    banner: false
    db-config:
      table-prefix: t_
      # 数据库配置
      id-type: auto
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Qj683k2^11299%nkjb
    url: jdbc:mysql://127.0.0.1:3306/kuaisou_ai_bot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true
logging:
  level:
    com.db.bots: ERROR